# Local Docker Compose configuration.
version: "3.9"

volumes:
  general-cache:
  general-datastore:
  general-datastore-pgadmin:
  kafka-broker-data:
  kafka-cluster-data:
  kafka-cluster-logs:
  pipeline-database:

networks:
  &general-database-network general-database-network:
  &kafka-network kafka-network:

services:
  &general-datastore general-datastore:
    image: postgres:15.3-alpine3.17
    hostname: *general-datastore
    container_name: *general-datastore
    networks:
      - *general-database-network
    volumes:
      - $PWD/services/datastores/general/setup:/docker-entrypoint-initdb.d
      - general-datastore:/var/lib/postgresql/data
    ports:
      - "6000:5432"
    environment:
      - POSTGRES_DB=restroy
      - POSTGRES_USER=restroy_admin
      - POSTGRES_PASSWORD=password123
    command: postgres -c max_connections=200 -c statement_timeout=60s -c idle_in_transaction_session_timeout=60s
    restart: on-failure

  &general-datastore-pgadmin general-datastore-pgadmin:
    image: dpage/pgadmin4:7.2
    container_name: *general-datastore-pgadmin
    hostname: *general-datastore-pgadmin
    profiles: ["pgadmin"]
    restart: always
    networks:
      - *general-database-network
    depends_on:
      - *general-datastore
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@restroy.com
      PGADMIN_DEFAULT_PASSWORD: password123
    ports:
      - "6001:80"
    volumes:
      - general-datastore-pgadmin:/var/lib/pgadmin

  &database-migration-tool database-migration-tool:
    container_name: *database-migration-tool
    hostname: *database-migration-tool
    profiles: ["ignore"]
    image: migrate/migrate:v4.14.1
    working_dir: /usr/local/migrations
    user: 1000:1000
    command: -verbose -database "postgresql://restroy_admin:password123@general-datastore:5432/restroy?sslmode=disable" -path "/usr/local/migrations/" up
    networks:
      - *general-database-network
    depends_on:
      - *general-datastore
    volumes:
      - $PWD/services/datastores/general/migrations:/usr/local/migrations
      - $PWD/services/datastores/general/seeds:/usr/local/seeds

  &general-cache general-cache:
    container_name: *general-cache
    hostname: *general-cache
    image: "redis:7.2-rc2-alpine3.18"
    command: redis-server
    ports:
      - "6010:6379"
    volumes:
      - general-cache:/var/lib/redis
    environment:
      - REDIS_REPLICATION_MODE=master

  &kafka-cluster kafka-cluster:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: *kafka-cluster
    hostname: *kafka-cluster
    ports:
      - "6020:2181"
    networks:
      - *kafka-network
    volumes:
      - kafka-cluster-data:/var/lib/zookeeper/data
      - kafka-cluster-logs:/var/lib/zookeeper/log
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  &kafka-broker kafka-broker:
    image: confluentinc/cp-kafka:7.4.0
    container_name: *kafka-broker
    hostname: *kafka-broker
    ports:
      - "9093:9093"
    depends_on:
      - *kafka-cluster
    networks:
      - *kafka-network
    volumes:
      - kafka-broker-data:/var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: kafka-cluster:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:29092,PLAINTEXT_HOST://localhost:9093
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100

  &kafka-ui kafka-ui:
    container_name: *kafka-ui
    hostname: *kafka-ui
    image: provectuslabs/kafka-ui:73bd6ca3a5ae599a986b1268239221526e63deaf
    profiles: ["kafkaui"]
    ports:
      - 6030:8090
    networks:
      - *kafka-network
    depends_on:
      - *kafka-broker
      - *kafka-cluster
    restart: on-failure
    environment:
      SERVER_PORT: 8090
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-broker:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: kafka-cluster:2181

  &api-gateway api-gateway:
    container_name: *api-gateway
    hostname: *api-gateway
    image: nginx:1.25.0-alpine3.17-slim
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 6050:80
    volumes:
      - $PWD/services/gateway/nginx.conf:/etc/nginx/nginx.conf
