packages:
  - "packages/pipeline-utils"
  - "packages/config-utils"
  - "packages/kafka-client"
  - "packages/clients"
  - "packages/core"
  - "services/pipelines/scheduler"
  - "services/pipelines/runner"
  - "services/apis/general"
