DROP INDEX workspace_management.role_permissions_role_id;
DROP INDEX workspace_management.team_members_team_id;
DROP INDEX workspace_management.team_members_user_id;
DROP INDEX workspace_management.boards_users_board_id;
DROP INDEX workspace_management.boards_users_user_id;
DROP INDEX workspace_management.pipeline_history_pipeline_id;
